### ISSUE TITLE
ToDo list

### ISSUE THREAD

**Issue by lior9005** [lior9005/Ass2#13]
- [ ] **make the ai work good**
     - [ ] need to call the method keyPressed
     - [ ] penalize the ai aswell
     - [ ] ai doesnt wait till board is filled (problem with the method keyPressed)

- [ ] **make the threads run smooth**
    - [ ] keyPressed checks and "if" statement

- [ ] **adjust bugs (runtime jumping etc)**
    - [ ] penalty countdown is jumping
  
- [ ] **bonus questions**
